✨ Auth 모듈 구현
KTB-Sixmen/gitfolio_back_spring pull request #12
Opened 2024-10-09 09:06 UTC by namkikim0718

## #️⃣연관된 이슈

- close #11 

## 📝작업 내용

- 깃허브 OAuth2.0을 활용한 소셜 로그인 구현을 완료했습니다.
- 토큰 저장소로 Redis를 사용했습니다.
- 토큰 재발급 로직인 reissue 관련 기능을 구현했습니다.
- 로그아웃 필터를 구현했습니다.
- Member 모듈과의 통신을 위한 WebClient 관련 설정 및 테스트를 완료했습니다.

## 💬리뷰 요구사항

- 로그인은 백엔드로의 별다른 요청이 아닌 하이퍼 링크로 진행됩니다. (ex. "{{base_url}}/oauth2/authorization/github")
- 프론트 개발 시 로그인 성공시 리다이렉트 URL를 설정해야합니다. 지금은 임의의 URL로 설정되어 있습니다.
- 소셜 로그인은 하이퍼링크로 진행되기 때문에 리다이렉트하면서 헤더에 AccessToken을 반환할 수 없으므로, 로그인 성공시 RefreshToken만 쿠키로 전달합니다.
- 쿠키는 httpOnly 설정이 되어있어 js로 직접 조작은 불가합니다. 그래서 백엔드로 reissue 요청을 별도로 보내 헤더에 AccessToken을 담는 과정을 진행해야합니다.
- 흐름은 아래와 같습니다.
  1. 하이퍼 링크를 통한 소셜 로그인 시도
  2. 로그인 성공 시 refreshToken을 쿠키에 담아서 리다이렉트
  3. 프론트에서 쿠키를 담아서 백엔드로 다시 reissue 요청
  4. 백엔드에서 토큰 검증 후 헤더에 AccessToken을 담아서 반환

2024-10-09 13:23 UTC, speardragon commented on gitfolio-auth/src/main/java/com/be/gitfolio/auth/oauth2/CustomSuccessHandler.java
> +        response.sendRedirect("http://localhost:5173/chat");
이 부분이 프론트 리다이렉트 부분인가요?? 일단 application.yml에 추가해서 관리하는 것도 좋을 것 같습니다!

2024-10-09 13:28 UTC, speardragon requested changes
고생하셨습니다! 코멘트 한 번 확인 부탁드려요

2024-10-09 13:28 UTC, speardragon commented on gitfolio-auth/src/main/java/com/be/gitfolio/auth/oauth2/CustomSuccessHandler.java
> +        String refresh = jwtUtil.createJwt("refresh", username, role, memberId,86400000L);
JWT 만료 시간 값에 대한 부분을 상수로 따로 빼서 관리하면 더 직관적일 것 같아요!

2024-10-09 13:28 UTC, speardragon commented on gitfolio-auth/src/main/java/com/be/gitfolio/auth/service/CustomOAuth2UserService.java
> +        this.webClient = webClientBuilder.baseUrl("http://localhost:8081").build();
8081번 포트는 common 모듈 포트인가요?? 이 부분도 applcation.yml로 빼서 관리하면 좋을 것 같습니당

2024-10-09 13:28 UTC, speardragon commented on gitfolio-auth/src/main/java/com/be/gitfolio/auth/oauth2/CustomSuccessHandler.java
> +        response.sendRedirect("http://localhost:5173/chat");
이 부분이 프론트 리다이렉트 부분인가요?? 일단 application.yml에 추가해서 관리하는 것도 좋을 것 같습니다!

2024-10-10 05:34 UTC, namkikim0718 commented on gitfolio-auth/src/main/java/com/be/gitfolio/auth/service/CustomOAuth2UserService.java
> +        this.webClient = webClientBuilder.baseUrl("http://localhost:8081").build();
8081은 일단 member 모듈 포트입니다!

2024-10-10 05:34 UTC, namkikim0718 commented on gitfolio-auth/src/main/java/com/be/gitfolio/auth/oauth2/CustomSuccessHandler.java
> +        response.sendRedirect("http://localhost:5173/chat");
위에 내용들 참고해서 전체적으로 수정할 부분 수정하도록하겠습니다~

2024-10-10 06:27 UTC, namkikim0718 commented
수정해야하는 부분들 수정했습니다!

2024-10-10 08:27 UTC, speardragon approved these changes
고생하셨습니다~~

2024-10-10 09:04 UTC, merged