✨ 결제 플랜에 따른 잔여 횟수 관리
KTB-Sixmen/gitfolio_back_spring pull request #86
Opened 2024-11-26 08:31 UTC by namkikim0718

## #️⃣연관된 이슈

- close #85 

## 📝작업 내용

- gRPC 관련 로직은 사용하지 않으므로 삭제 했습니다.
- 기존 단건 결제에서 정기 결제로 변경했습니다.
- 무료 플랜 사용자에게 하루에 3개의 사용권만 사용가능하도록 설정했습니다.
- 유료 플랜 사용자는 한달동안 무제한으로 사용할 수 있도록 설정했습니다.
- 사용권과 정기 결제 관리를 위해 Spring Batch를 도입했습니다.
- AI 기반 이력서 수정 로직을 더미 데이터로 우선 구현해두었습니다.
- 알림에 senderNickname을 추가했습니다.
- 프론트에 시간 띄우는 경우 UTC 시간으로 나오는 경우가 있어서 KST로 설정했습니다. (로컬에서는 오히려 안맞을 수도 있음)

- 배치 작업은 다음과 같이 이루어집니다.
    1. 매일 자정 Payment 배치 작업 시작
    2. 순회하며 오늘로 결제 플랜 만료일이 된 사람들 중 계속 구독 중인 사람은 정기 결제 요청을 전송
    3. 만료된 사람들 중 해지한 사람들은 Payment 테이블에서 삭제하고 Member모듈로 이벤트 발생해 FREE 플랜으로 변경
    4. Payment 모듈의 배치작업이 완료되면 작업 완료 이벤트를 발생
    5. 해당 이벤트 발생 시 Member 모듈 배치작업 시작
    6. FREE인 사용자들의 잔여 사용권을 3으로 전부 리셋 (PRO 플랜은 잔여 사용권 관리 X)

2024-11-26 10:57 UTC, speardragon requested changes
고생하셨습니다! 리뷰 확인 부탁드려요!

2024-11-26 10:57 UTC, speardragon commented on gitfolio-member/src/main/java/com/be/gitfolio/member/domain/Member.java
여기 코드 뭔가 리팩토링 할 수 있는 방법이 있지 않을까요?? 모든 필드들에 대해서 build하는 것 하나 만들고 가져다 쓰는 식으로?

```
    public Member decreaseRemainingCount() {
        return commonBuilder()
                .remainingCount(remainingCount - 1)
                .updatedAt(LocalDateTime.now())
                .build();
    }
```
이런 느낌일 것 같은데 어떻게 생각하시나요?

2024-11-26 10:57 UTC, speardragon commented on gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeResponseDTO.java
타임존 변환 로직이 생각보다 복잡한데 유틸함수로 따로 빼서 사용해도 좋을 것 같아요!

2024-11-26 10:59 UTC, speardragon commented
그리고 프론트 쪽에서는 이력서 생성 요청이나 수정 요청 시에 사용권 차감 API를 같이 보내주는 방식으로 해야 하는 건가요??

2024-11-27 07:23 UTC, namkikim0718 commented on gitfolio-member/src/main/java/com/be/gitfolio/member/domain/Member.java
관련내용 toBuilder() 를 통해서 코드 단순화 하겠습니다!!

2024-11-27 07:30 UTC, namkikim0718 commented on gitfolio-resume/src/main/java/com/be/gitfolio/resume/dto/ResumeResponseDTO.java
따로 빼서 사용하도록 하겠습니다!

2024-11-27 12:28 UTC, speardragon approved these changes
오오 좋습니다! 고생하셨습니다!

2024-11-28 08:17 UTC, merged